version: '3.8'

services:
  s_api:
    image: api_image
    container_name: c_api
    build:
      context: .
      dockerfile:  src/DrMW.Cqrs.Api/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  
   
    
