name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./src/DrMW.Cqrs.Api --file src/DrMW.Cqrs.Api/Dockerfile --tag my-image-name:$(date +%s)
      

