name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Repo'yu Kontrol Et
      uses: actions/checkout@v4

    - name: Docker Buildx Kurulumu
      uses: docker/setup-buildx-action@v1

    - name: Docker Compose ile Hizmetleri Başlat
      run: |
        docker-compose -f docker-compose.yml up --build -d

      

